version: '3.7'

services:
  system-hospital:
    image: postgres:15.3
    container_name: system-hospital
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231020
      POSTGRES_DB: db_hospital
    ports:
      - "5432:5432"

volumes:
  postgres_data:
